apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9121"
spec:
  ports:
    - port: 6379
      name: redis
    - port: 9121
      name: metrics
  clusterIP: None
  selector:
    app: redis
